export ZSH="$HOME/.oh-my-zsh"
export HISTFILE="$HOME/.oh-my-zsh/.zsh_history"
export ZSH_COMPDUMP=$ZSH/cache/.zcompdump-$HOST

plugins=(
  colored-man-pages
  copyfile
  copypath
  sudo
  vi-mode
  zoxide
  zsh-autopair
  zsh-autosuggestions
  zsh-syntax-highlighting
)
source $ZSH/oh-my-zsh.sh
source /usr/share/nvm/init-nvm.sh
export PATH=$PATH:~/.local/bin/
eval "$(oh-my-posh init zsh --config ~/.config/posh_themes/mod_theme.yaml)"

if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ]; then
  tmux new-session -A -s main
fi
