export HISTFILE="$HOME/.zsh/.zsh_history"
export ZSH_COMPDUMP=$ZSH/cache/.zcompdump-$HOST
export ZSH="$HOME/.zsh/oh-my-zsh"
ZSH_THEME=""
HYPHEN_INSENSITIVE="true"

plugins=(
  git
  colored-man-pages
  copypath
  copyfile
  sudo
  vi-mode
  web-search
  zoxide
  zsh-autopair
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
fi
  export EDITOR='nvim'

eval "$(oh-my-posh init zsh --config ~/.posh_themes/gruvbox.omp.json)"
source /usr/share/nvm/init-nvm.sh
